# -*- coding: utf-8 -*-
"""All site copy and data in one place. build.py turns this into HTML."""

SITE_URL = "https://cgaindia.com"

FIRM = {
    "legal": "Canjain Global Advisors Pvt Ltd",
    "short": "Canjain Global Advisors",
    "phone": "+91 98999 00300",
    "phone_href": "+919899900300",
    "phone2": "+91 99966 47888",
    "phone2_href": "+919996647888",
    "wa": "919899900300",
    "email_sales": "arm@cgaindia.com",
    "email_support": "help@cgaindia.com",
    "email_careers": "admin@cgaindia.com",
    "pay": "https://rzp.io/rzp/ehe2M4d",
    "fb": "https://www.facebook.com/profile.php?id=100081348033294",
    "ig": "https://www.instagram.com/canjain_",
    "yt": "https://www.youtube.com/@canjain",
    "head_office": "Aparna Tower, near Old Bus Stand, Mathura, Uttar Pradesh",
    "tagline": "Every registration, return and licence your business owes — filed on time.",
}

OFFICES = [
    ("Head office", "Mathura", "Aparna Tower, near Old Bus Stand,<br>Mathura, Uttar Pradesh"),
    ("Branch", "Delhi — Burari", "Burari,<br>Delhi 110084"),
    ("Branch", "Delhi — Laxmi Nagar", "Laxmi Nagar,<br>East Delhi"),
    ("Branch", "Rohtak", "Rohtak,<br>Haryana"),
    ("Branch", "Safidon", "Safidon,<br>District Jind, Haryana"),
]

# (name, role, qualification, phone-or-empty, photo-file)
TEAM = {
    "Leadership": [
        ("Neeraj Jain", "Founder &amp; CEO", "Advocate", "", "neeraj.jpg"),
    ],
    "Senior executives — your primary point of contact": [
        ("Naveen Kumar", "Senior Executive", "BA (Mathematics) · 6+ years", "+918750049000", "naveen-kumar.jpg"),
        ("Krishan Kumar", "Senior Executive", "M.Com · 5+ years", "+918585973030", "krishan-kumar.jpg"),
        ("Suresh Kumar", "Senior Executive", "MBA (pursuing) · 5+ years", "+919811585811", "suresh-kumar.jpg"),
        ("Shrey Jain", "Senior Executive", "CA Final · 3+ years", "+919896100158", "shrey-jain.jpg"),
        ("Pankaj", "Senior Executive", "B.Com · 3+ years", "", "pankaj.jpg"),
    ],
    "Assistants": [
        ("Ranjay", "Assistant", "B.Com", "", "ranjay.jpg"),
        ("Ravi", "Assistant", "BA (pursuing)", "", "ravi.jpg"),
        ("Hemant Sharma", "Assistant", "B.Tech (Computer Engineering)", "", "hemant-sharma.jpg"),
        ("Sanjay Kumar", "Assistant", "M.Com", "", "sanjay-kumar.jpg"),
        ("Deepak", "Assistant", "", "", "deepak.jpg"),
        ("Shubham", "Assistant", "", "", "shubham.jpg"),
    ],
    "Junior assistants": [
        ("Anurag", "Junior Assistant", "BCA (pursuing)", "", "anurag.jpg"),
        ("Ankit", "Junior Assistant", "B.Sc Computer Science", "", "ankit.jpg"),
        ("Ritu", "Junior Assistant", "B.Com", "", "ritu.jpg"),
        ("Kafi", "Junior Assistant", "B.Com", "", "kafi.jpg"),
        ("Rahul", "Junior Assistant", "B.Com", "", "rahul.jpg"),
        ("Sushil", "Junior Assistant", "M.A. (English)", "", "sushil.jpg"),
        ("Suman", "Junior Assistant", "B.Com", "", "suman.jpg"),
    ],
}

SERVICE_OPTIONS = [
    "Not sure yet — please advise",
    "Company / LLP registration",
    "GST registration or returns",
    "TDS returns",
    "Income tax return or notice",
    "ROC annual compliance",
    "Trademark, copyright or patent",
    "FSSAI, ISO or other licence",
    "NBFC / RBI approval",
    "Environment / EPR",
    "CMA data or project report",
    "Legal notice or agreement",
]

# ----------------------------------------------------------------------
# Service pages
# ----------------------------------------------------------------------

SERVICES = [
# ---------------------------------------------------------------- ITR
{
"slug": "itr-filing",
"nav": "tax",
"name": "Income tax return filing",
"short": "Income tax returns",
"authority": "CBDT · e-filing portal",
"title": "Income Tax Return Filing — Individuals, Firms &amp; Companies",
"meta": "ITR preparation and filing for salaried individuals, businesses, firms and companies, including capital gains, house property and NRI returns, with a computation you can read.",
"reg": "Individuals, firms and companies, reconciled against 26AS and the AIS.",
"lead": "Returns prepared from your actual documents, reconciled against Form 26AS and the AIS, and filed with a computation you can actually read.",
"intro": [
  "Most return trouble does not start at filing. It starts when what you declared does not match what the department already has — the AIS and Form 26AS carry your salary, interest, dividends, property transactions, mutual fund sales and TDS long before you sit down to file. We reconcile against both first, prepare the return, then tell you what the tax works out to and why.",
  "Regime selection matters more than most people expect. The new regime is the default, and for a business assessee moving out of it involves Form 10-IEA and a choice that is not freely reversible year after year. We run the numbers both ways before choosing one.",
],
"handle": [
  "Selecting the correct form — ITR-1 through ITR-7 — for your income mix and residential status",
  "Reconciliation with Form 26AS, AIS and TIS before anything is filed",
  "Old regime versus new regime comparison, with Form 10-IEA where a business assessee opts out",
  "Salary, house property, business and profession, capital gains and other sources",
  "Presumptive taxation under sections 44AD, 44ADA and 44AE where it applies",
  "Carry-forward of losses, and the deadlines that decide whether you keep them",
  "Advance tax and self-assessment tax computation, with challan payment",
  "E-verification, refund tracking and rectification where processing throws up a mismatch",
  "Revised and updated returns, including ITR-U for earlier years",
  "Replies to intimations and scrutiny notices arising from the return",
],
"supply": [
  "PAN and Aadhaar, and the mobile number linked to Aadhaar for e-verification",
  "Form 16 from each employer for the year, if salaried",
  "Bank account details and interest certificates",
  "Capital gains statements from your broker or mutual fund, or property sale documents",
  "Books, bank statements and turnover summary, if you run a business or profession",
  "Proofs for the deductions you intend to claim, if you are on the old regime",
  "Last year's acknowledgement and computation, if you have it",
],
"supply_note": "If some of this is missing, say so on the call rather than delaying — a good part of it can be pulled from the portal, and we will tell you exactly what only you can supply.",
"callout": ("Talk to us first", "Filed late, or not at all?",
  "A missed year is usually fixable. An updated return under ITR-U is available for earlier years on payment of additional tax, and it costs far less than waiting for a notice to arrive."),
"steps": [
  ("Documents and access", "You send what you have. We pull the AIS, 26AS and pre-filled data and list anything still missing."),
  ("Computation shared", "You receive the computation and the tax payable or refund due — before filing, not after."),
  ("Tax paid and return filed", "Any balance tax is paid by challan, the return is filed and the acknowledgement comes to you."),
  ("Verified and tracked", "E-verification is completed within the window, then we watch processing and the refund until it lands."),
],
"faqs": [
  ("Do I have to file if my income is below the exemption limit?",
   "Not always — but filing is compulsory in several situations regardless of income, including where large deposits, high electricity spend or foreign travel expenditure cross the prescribed thresholds, and where you hold foreign assets. It is also the simplest way to claim a refund of TDS already deducted."),
  ("What happens if I file after the due date?",
   "A late fee under section 234F applies, interest runs on unpaid tax, and certain losses can no longer be carried forward. The return can still be filed as a belated return within the allowed window, and beyond that an updated return may be possible."),
  ("Can you handle a return with capital gains from shares and crypto together?",
   "Yes. Listed equity, mutual funds and property follow the normal capital gains rules; virtual digital assets are taxed separately under their own regime with no set-off of losses. They sit in the same return but are computed differently."),
  ("I have received a notice about my return. Is that the same work?",
   "No, that is a separate engagement and it is time-bound. Send the notice across before the reply window closes and we will tell you how serious it is and quote for the reply."),
],
"related": ["tds-returns", "crypto-tax", "foreign-income", "gst-return-filing"],
"cta": ("Send us last year's return and this year's documents",
        "You do not have to know the name of the form. Describe the situation and we will identify the filing, the authority and a realistic timeline before you pay anything."),
},
# ---------------------------------------------------------------- TDS
{
"slug": "tds-returns",
"nav": "tax",
"name": "TDS computation and returns",
"short": "TDS returns",
"authority": "CBDT · TRACES",
"title": "TDS Computation &amp; Quarterly Returns — 24Q, 26Q, 27Q",
"meta": "Section-wise TDS computation, challan mapping, quarterly returns in Forms 24Q, 26Q and 27Q, Form 16 and 16A issue, and correction statements for defaults.",
"reg": "Section-wise computation, challan mapping, 24Q/26Q/27Q and Form 16.",
"lead": "Deduct at the right rate under the right section, deposit on time, and file a return that does not come back as a default six months later.",
"intro": [
  "Most TDS demands are not caused by non-payment. They are caused by a PAN typed wrong, a challan mapped to the wrong quarter, or a payment deducted under the wrong section — small clerical facts that TRACES turns into interest and a short-deduction notice.",
  "We treat the return as the last step, not the first. The section, the rate, the threshold and the challan are settled when the payment is made, so the quarterly filing becomes an assembly job rather than a reconstruction.",
],
"handle": [
  "Section-wise applicability — 192, 194A, 194C, 194H, 194I, 194J, 194Q, 194-IA, 194-IB and 195",
  "Rate and threshold checks, including higher rates for non-filers and missing PAN",
  "Monthly deposit by challan, with the section and assessment year checked before payment",
  "Quarterly returns in Form 24Q, 26Q and 27Q, and 27EQ for TCS",
  "Form 16 and Form 16A generation and issue to deductees",
  "Correction statements for PAN errors, challan mismatch and short deduction",
  "Lower or nil deduction certificates under section 197",
  "Section 194-IA on property purchase, including Form 26QB and the buyer's Form 16B",
  "Reply to TRACES default notices, late fee under 234E and interest computation",
  "Salary TDS working for employers, including regime declarations from employees",
],
"supply": [
  "TAN, and PAN of the entity",
  "Vendor and employee PAN list with payment details for the quarter",
  "Challans already paid, with BSR code, date and serial number",
  "Salary structure and employee declarations, for 24Q",
  "Previous quarter's return and any TRACES notice received",
],
"supply_note": "If you are unsure whether a payment attracted TDS at all, send the invoice — the section is easier to settle from the document than from a description.",
"callout": ("Before the quarter closes", "Already received a default notice?",
  "Short deduction, short payment and late fee notices are usually resolvable through a correction statement rather than payment. Send the notice and the original return, and we will tell you which of the three it actually is."),
"steps": [
  ("Payment review", "We look at what was paid to whom during the quarter and fix the section and rate for each head."),
  ("Deposit and mapping", "Challans are paid or verified, and each deduction is mapped to the correct challan before the return is built."),
  ("Return filed", "The quarterly statement is filed and the token number shared with you."),
  ("Certificates and follow-up", "Form 16 or 16A is downloaded and issued, and we watch TRACES for defaults raised on processing."),
],
"faqs": [
  ("We deducted the tax but deposited it late. How bad is that?",
   "Interest runs under section 201(1A) from the date of deduction to the date of deposit, and the expenditure can be disallowed in some situations until the deposit is made. It is far better resolved now than at assessment."),
  ("Do we need to file a return for a quarter with no deductions?",
   "There is no return to file if nothing was deducted, but filing a declaration of non-filing on TRACES for that quarter prevents the system from treating it as a pending return and issuing reminders."),
  ("A vendor says the credit is not showing in their 26AS.",
   "That is almost always a PAN error or an unmapped challan in the return. It is fixed by a correction statement, and the credit then flows to the vendor for the same quarter."),
  ("I bought a flat. Is this the service I need?",
   "Yes, in part. A buyer must deduct under section 194-IA and file Form 26QB, then issue Form 16B to the seller. We handle that, including cases where the deduction was missed and interest has to be worked out."),
],
"related": ["itr-filing", "gst-return-filing", "roc-annual-compliance", "international-tax"],
"cta": ("Send us last quarter's return and this quarter's payment list",
        "We will tell you what was deducted correctly, what was not, and what it costs to fix — before any filing."),
},
# ---------------------------------------------------------------- GST REG
{
"slug": "gst-registration",
"nav": "tax",
"name": "GST registration",
"short": "GST registration",
"authority": "CBIC · GST portal",
"title": "GST Registration — New GSTIN, Amendment &amp; Clarification Replies",
"meta": "GST registration for businesses, e-commerce sellers, casual and non-resident taxable persons — application, clarification replies, amendments and revocation of cancellation.",
"reg": "Application, clarification replies and GSTIN, including e-commerce sellers.",
"lead": "The application is the easy part. Getting through physical verification and the clarification notice without losing three weeks is the work.",
"intro": [
  "Registration is granted on documents, not on intention. Most rejections and REG-03 clarification notices come down to three things: a principal place of business the officer cannot connect to the applicant, a rent agreement or electricity bill in a name that does not match, or a business activity that does not fit the HSN and constitution declared.",
  "We check applicability before applying. Threshold, state, inter-state supply, e-commerce sale and reverse charge each change the answer, and a registration taken when none was required creates a permanent return obligation.",
],
"handle": [
  "Applicability review — turnover threshold, state, inter-state supply and compulsory registration cases",
  "Regular, composition, casual taxable person and non-resident taxable person registration",
  "Application in Form REG-01 with document preparation and Aadhaar authentication",
  "Reply to clarification notices in Form REG-03 within the reply window",
  "Physical verification support, including premises documentation",
  "Additional place of business, and multi-state registration for sellers holding stock elsewhere",
  "Amendment of core and non-core fields — address, partners, directors, business activity",
  "Revocation of cancelled registration, and reply to cancellation notices in Form REG-17",
  "Voluntary registration where a buyer insists on it, with the obligations explained first",
  "Input service distributor and e-commerce operator registration where applicable",
],
"supply": [
  "PAN of the business, and of every partner, director or proprietor",
  "Aadhaar of the authorised signatory, with the linked mobile number",
  "Proof of principal place of business — ownership document, rent agreement, or a consent letter with the owner's document",
  "A recent electricity bill, property tax receipt or municipal record for the premises",
  "Constitution document — partnership deed, certificate of incorporation, or society or trust deed",
  "Bank account proof — cancelled cheque or the first page of the statement",
  "Photographs of the proprietor, partners or directors",
],
"supply_note": "Where the premises is taken from a family member without a written agreement, say so at the start. That situation has a standard fix, but not one that can be improvised after the notice arrives.",
"callout": ("Time-bound", "Registration suspended or cancelled?",
  "A suspension under Form REG-17 carries a short reply window, and revocation gets harder once returns pile up behind it. Send the notice the day it arrives."),
"steps": [
  ("Applicability check", "We confirm whether you must register, may register, or should not — and in which states."),
  ("Documents assembled", "Premises, constitution and identity documents are checked against each other before anything is uploaded."),
  ("Application and clarification", "REG-01 is filed. If a clarification notice comes, the reply goes in within the window with supporting documents."),
  ("GSTIN and first return", "The certificate is shared along with your return calendar, so the first filing does not slip."),
],
"faqs": [
  ("What is the turnover limit for registration?",
   "It depends on the state and on whether you supply goods, services or both, and the special category states have their own limit. Several situations require registration regardless of turnover — inter-state supply of goods, e-commerce sale, and liability under reverse charge among them. We confirm your position before applying."),
  ("How long does registration take?",
   "Where Aadhaar authentication succeeds and the documents are consistent, it is usually a matter of days. A clarification notice or physical verification adds to that, which is exactly why the document check happens before filing."),
  ("Can I register from home?",
   "Yes, a residential address can be the principal place of business, supported by an ownership document or a consent letter from the owner along with proof of their ownership."),
  ("Do I need separate registration in each state?",
   "Registration is state-wise. If you hold stock or have a place of business in another state — including inventory at a marketplace warehouse — that state needs its own registration."),
],
"related": ["gst-return-filing", "ecommerce-sellers", "itr-filing", "pvt-ltd-registration"],
"cta": ("Tell us what you sell and from where",
        "Two facts — the nature of supply and the states involved — usually settle whether you need one registration or four."),
},
# ---------------------------------------------------------------- GST RET
{
"slug": "gst-return-filing",
"nav": "tax",
"name": "GST return filing",
"short": "GST returns",
"authority": "CBIC · GST portal",
"title": "GST Return Filing — GSTR-1, GSTR-3B, 2B Reconciliation &amp; Annual Return",
"meta": "Monthly and quarterly GST returns with GSTR-2B reconciliation, input tax credit review, GSTR-9 and 9C annual filing, and replies to ASMT-10 and DRC-01 notices.",
"reg": "GSTR-1 and 3B with 2B reconciliation and input credit review.",
"lead": "A fixed monthly cycle, with credit reconciled against GSTR-2B before the return goes in rather than after a notice asks why it did not match.",
"intro": [
  "Input tax credit is now a function of what your supplier filed, not of what you paid. If a vendor misses GSTR-1, the credit does not appear in your 2B and claiming it anyway creates an exposure that surfaces months later as a mismatch notice.",
  "So reconciliation comes before filing, every month, and the vendors who are costing you credit are named while there is still time to chase them.",
],
"handle": [
  "GSTR-1 and GSTR-3B on the monthly cycle, and the QRMP quarterly cycle with monthly payment",
  "GSTR-2B reconciliation against purchase records, with a vendor-wise list of missing credit",
  "Input tax credit eligibility review, including blocked credit under section 17(5)",
  "Reversal working under rules 42 and 43 for exempt and personal use",
  "Output liability review — rate, place of supply, and reverse charge on notified supplies",
  "Annual return in GSTR-9 and reconciliation statement in GSTR-9C where applicable",
  "E-invoice and e-way bill compliance checks where turnover crosses the threshold",
  "Amendment of earlier returns, and credit note treatment within the allowed window",
  "Reply to scrutiny notices in ASMT-10, and to demands in DRC-01 and DRC-01A",
  "Refund applications — export without payment of tax, inverted duty structure and excess balance",
],
"supply": [
  "Sales register for the period, with invoice-wise details",
  "Purchase register, with supplier GSTIN and invoice numbers",
  "Bank statements for the period",
  "Debit and credit notes issued and received",
  "Details of any advance received, and of exempt or non-GST supply",
  "Portal credentials, or access as an authorised representative",
],
"supply_note": "If your accounting software exports the sales and purchase registers directly, send those files. Re-keying data is where errors enter.",
"callout": ("Every month, before filing", "The vendors quietly costing you credit",
  "Reconciliation produces a list of suppliers whose invoices are not in your 2B. Sent to them in the same month, most of it is recovered. Sent at year end, much of it is not."),
"steps": [
  ("Registers in by a fixed date", "You send sales and purchase data on an agreed day each month, not when the deadline is near."),
  ("Reconciled against 2B", "Credit is matched, the gap is listed vendor-wise, and the ineligible portion is flagged."),
  ("Liability confirmed", "You approve the tax payable figure before payment — no surprises at the portal."),
  ("Filed and acknowledged", "Returns are filed, acknowledgements shared, and the next month's dates confirmed."),
],
"faqs": [
  ("Can I claim credit that is not showing in my GSTR-2B?",
   "The law ties credit to what appears in your auto-populated statement, subject to the other conditions being met. The practical answer is to get the supplier to report the invoice rather than to claim and defend it later."),
  ("What if a return for an earlier month was never filed?",
   "Returns are sequential — a gap blocks the ones after it, late fee and interest accumulate, and prolonged non-filing can lead to suspension of the registration. It is usually cheaper to clear the backlog than to carry it."),
  ("Do we need GSTR-9C?",
   "The annual return and the reconciliation statement have separate turnover thresholds, and they change from time to time. We confirm your position for the year before preparing either."),
  ("We received an ASMT-10 asking about a difference between 3B and 2A.",
   "That is a scrutiny notice with a reply window. Most of these are explained by timing differences or credit notes. Send it across with the return data and we will draft the reply."),
],
"related": ["gst-registration", "ecommerce-sellers", "tds-returns", "itr-filing"],
"cta": ("Send us three months of returns",
        "We will tell you what credit you are losing, where the liability is understated, and what a clean monthly cycle would cost."),
},
# ---------------------------------------------------------------- CRYPTO
{
"slug": "crypto-tax",
"nav": "specialist",
"name": "Crypto and VDA taxation",
"short": "Crypto / VDA tax",
"authority": "CBDT · section 115BBH",
"title": "Crypto &amp; VDA Taxation — Section 115BBH, TDS 194S and Schedule VDA",
"meta": "Taxation of virtual digital assets: flat-rate computation under section 115BBH, TDS credit under 194S, Schedule VDA reporting, exchange statement reconciliation and foreign exchange holdings.",
"reg": "Section 115BBH computation, 194S credit and Schedule VDA.",
"lead": "Gains on virtual digital assets are taxed under their own regime — flat rate, no set-off of losses, and a schedule in the return that has to match your exchange statements.",
"intro": [
  "The rules for virtual digital assets do not follow ordinary capital gains. Income is taxed at a flat rate with only the cost of acquisition allowed as a deduction, loss from one asset cannot be set off against gain from another, and nothing can be carried forward. A profitable year and a loss-making year can both produce tax.",
  "The reporting side is where most people get caught. Exchanges deduct tax under section 194S and report it, so the department already has a picture of your trading before you file. If Schedule VDA does not reconcile with that, the return invites questions.",
],
"handle": [
  "Transaction-wise computation under section 115BBH from exchange and wallet statements",
  "Cost of acquisition working, including transfers between wallets and exchanges",
  "Schedule VDA preparation, matched to the transaction record",
  "TDS credit under section 194S reconciled against Form 26AS and the AIS",
  "Treatment of airdrops, staking rewards, mining receipts and gifts of digital assets",
  "Peer-to-peer and foreign exchange transactions, including bank enquiry replies",
  "Schedule FA reporting where assets are held on a foreign platform",
  "Income from trading treated as business income, where the facts support it",
  "Earlier years left unreported, through an updated return where available",
  "Replies to notices arising from AIS entries for digital asset transactions",
],
"supply": [
  "Full-year transaction statements from every exchange used, in the exported format",
  "Wallet addresses or statements for off-exchange holdings and transfers",
  "Bank statements covering deposits to and withdrawals from exchanges",
  "Details of any assets received as a gift, airdrop, staking reward or mining output",
  "Form 26AS and the AIS download for the year",
],
"supply_note": "Send the raw exported files rather than a summary. Cost of acquisition has to be traced transaction by transaction, and a summary cannot be audited back to source.",
"callout": ("Worth knowing", "A loss year can still produce a tax liability",
  "Because losses on one digital asset cannot be set off against gains on another, a portfolio that finished the year down can still carry tax on its winning trades. The computation has to be done trade-wise before you assume there is nothing to pay."),
"steps": [
  ("Statements collected", "Every exchange and wallet used during the year is listed, and the exports are collected in full."),
  ("Transaction-wise computation", "Gains are computed per transfer, with cost traced and internal transfers excluded."),
  ("Reconciled to AIS", "The result is matched against 194S credits and AIS entries so the return agrees with what is already reported."),
  ("Filed with Schedule VDA", "The return is filed with the schedule completed, and the working papers are kept if a question follows."),
],
"faqs": [
  ("Can I set off crypto losses against my salary or share gains?",
   "No. The regime for virtual digital assets does not permit set-off against other heads, and loss within the category cannot be carried forward either. This is the single biggest difference from ordinary capital gains."),
  ("The exchange already deducted TDS. Is my tax paid?",
   "No. Deduction under 194S is a credit against your liability, not the liability itself. It is generally a small percentage of the transaction value, while the tax is charged on the gain at a flat rate."),
  ("I traded on a foreign exchange. Does that change anything?",
   "It can add reporting obligations — holdings on a foreign platform may need to be disclosed in Schedule FA, and the remittance route matters. It is worth settling before filing rather than after."),
  ("I did not report earlier years. What now?",
   "Depending on how far back it goes, an updated return may be available on payment of additional tax. Given that exchange data is reported, voluntary correction is a far better position than waiting."),
],
"related": ["itr-filing", "foreign-income", "international-tax", "tds-returns"],
"cta": ("Send your exchange exports for the year",
        "We will produce the computation first and tell you the number before anything is filed."),
},
# ---------------------------------------------------------------- NRI
{
"slug": "foreign-income",
"nav": "specialist",
"name": "Foreign income and NRI taxation",
"short": "Foreign income &amp; NRI",
"authority": "CBDT · FEMA",
"title": "NRI Taxation &amp; Foreign Income — Residential Status, Schedule FA, DTAA",
"meta": "Residential status determination, foreign asset reporting in Schedule FA, DTAA relief and Form 67, NRO and NRE account taxation, and repatriation certificates in Form 15CA and 15CB.",
"reg": "Residential status, Schedule FA, DTAA relief and repatriation.",
"lead": "Residential status decides everything else. Get it right first, and the rest of an NRI return becomes ordinary work.",
"intro": [
  "Your status is a question of days present in India, tested against thresholds that changed in recent years and that treat Indian-source income differently. Two people with identical jobs abroad can end up with different statuses, and therefore with a different answer on whether foreign salary is taxable in India at all.",
  "The second half of the work is disclosure. Foreign bank accounts, shares, retirement accounts and property generally have to be reported by a resident even where no income arises from them, and the consequences of leaving them out are disproportionate to the tax involved.",
],
"handle": [
  "Residential status determination, including resident but not ordinarily resident cases",
  "Taxability of foreign salary, and relief where the same income is taxed in both countries",
  "Treaty relief under a DTAA, with Form 67 and the tax residency certificate",
  "Schedule FA reporting — foreign bank accounts, shares, retirement funds and immovable property",
  "NRO and NRE account interest, and TDS deducted by Indian banks on NRO income",
  "Capital gains on Indian shares, mutual funds and property held by a non-resident",
  "Sale of property in India by an NRI, including the buyer's withholding obligation",
  "Lower deduction certificates under section 197 where TDS exceeds the actual liability",
  "Repatriation of funds with Form 15CA and Form 15CB certification",
  "Returning Indians, and the year in which status changes",
],
"supply": [
  "Passport pages showing arrival and departure dates for the relevant years",
  "Overseas employment contract and salary statements",
  "Tax return and tax paid record in the other country, if claiming treaty relief",
  "Tax residency certificate from the other country's authority, where required",
  "Indian bank statements, including NRO and NRE accounts",
  "Details of foreign accounts, shares, pension funds and property held",
  "Sale documents and purchase records, if property is being sold",
],
"supply_note": "Day-count is the foundation of the whole return. Send travel dates before anything else, even if the rest of the documents take time.",
"callout": ("Before the sale, not after", "Selling property in India as an NRI?",
  "The buyer must withhold tax on the sale, and the rate applied to the sale value is often far higher than the tax actually due on your gain. A certificate under section 197 obtained before the transaction avoids locking up funds for a year waiting for a refund."),
"steps": [
  ("Status settled", "Day-count and the relevant tests are applied, and your status for the year is fixed in writing."),
  ("Income mapped", "Each source is classified as taxable in India or not, and treaty positions are identified."),
  ("Relief and disclosure", "Form 67, Schedule FA and the credit for foreign tax are prepared with supporting documents."),
  ("Filed and repatriation handled", "The return is filed, and where funds are moving out, 15CA and 15CB are issued."),
],
"faqs": [
  ("I am an NRI. Do I have to file a return in India at all?",
   "If you have income arising in India above the basic limit — rent, interest, capital gains, professional fees — then generally yes. Many NRIs also file to claim a refund of TDS deducted by banks at rates well above their actual liability."),
  ("Is my salary earned abroad taxable in India?",
   "For a non-resident, foreign salary for services rendered outside India generally is not. For a resident, worldwide income is taxable, with credit available for tax paid abroad under the relevant treaty. Which of the two you are is the whole question."),
  ("What is the risk of not reporting a foreign account?",
   "Non-disclosure of foreign assets by a resident is treated far more seriously than an ordinary omission, with its own penalty regime independent of the tax involved. The disclosure obligation applies even where the account earns nothing."),
  ("Can you handle everything without me coming to India?",
   "Yes. Documents are collected and returned digitally, signatures are managed through e-verification or a power of attorney where the authority requires one, and we deal with the bank directly on repatriation."),
],
"related": ["international-tax", "itr-filing", "crypto-tax", "tds-returns"],
"cta": ("Start with your travel dates",
        "Send arrival and departure dates for the year and the sources of income. Status first, everything else after."),
},
# ---------------------------------------------------------------- INTL
{
"slug": "international-tax",
"nav": "specialist",
"name": "International taxation",
"short": "International taxation",
"authority": "CBDT · RBI · FEMA",
"title": "International Taxation — Section 195, Form 15CA/CB, Transfer Pricing, FEMA",
"meta": "Cross-border withholding under section 195, Form 15CA and 15CB certification, transfer pricing documentation, permanent establishment exposure, FDI and ODI reporting under FEMA.",
"reg": "Section 195 withholding, 15CA/CB, transfer pricing and FEMA reporting.",
"lead": "Payments leaving India carry two separate questions — how much tax to withhold, and which reporting the transaction triggers. Both are settled before the remittance, not after.",
"intro": [
  "A foreign remittance can be a royalty, fees for technical services, business income or a capital account transaction, and each attracts a different treatment. The bank will not release the funds without a certificate, and a certificate issued on the wrong characterisation creates a liability on the payer, not the recipient.",
  "Where the parties are related, transfer pricing applies in addition. The requirement is not merely to price the transaction fairly but to be able to show, in prescribed form and at the right time, how the price was arrived at.",
],
"handle": [
  "Withholding under section 195 on payments to non-residents, with treaty rate applied where available",
  "Form 15CA and Form 15CB certification for remittances",
  "Characterisation of payments — royalty, fees for technical services, business profits, interest, dividend",
  "Permanent establishment and business connection exposure review",
  "Equalisation levy and digital transaction implications where relevant",
  "Transfer pricing study, benchmarking and documentation, with Form 3CEB",
  "Inbound structuring for a foreign parent setting up an Indian subsidiary or liaison office",
  "FDI reporting on the RBI FIRMS portal, including Form FC-GPR and FC-TRS",
  "Overseas direct investment reporting and the annual performance return",
  "Application for a lower or nil withholding certificate under section 195(2)",
],
"supply": [
  "The agreement or invoice underlying the remittance",
  "Tax residency certificate of the recipient, and Form 10F",
  "No permanent establishment declaration from the recipient, where applicable",
  "Details of the relationship between the parties, if any",
  "Board resolution and shareholding pattern, for capital account transactions",
  "Bank details and the purpose code proposed by the bank",
],
"supply_note": "Send the agreement before the invoice is raised where possible. The way a contract is drafted often decides the withholding rate more than the payment itself does.",
"callout": ("Before the remittance", "The bank has asked for 15CB and the payment is stuck",
  "This is the most common way the question arrives, and it is the worst time to answer it. The characterisation and treaty position can be settled in advance so the certificate is a formality rather than a delay."),
"steps": [
  ("Transaction reviewed", "The agreement and the parties are examined, and the nature of the payment is fixed."),
  ("Position taken in writing", "Treaty article, rate and reporting requirement are set out, with the documents needed from the recipient."),
  ("Certificate and remittance", "Form 15CB is certified, 15CA filed, and the bank is dealt with directly if it raises queries."),
  ("Annual reporting", "Form 3CEB, FLA and RBI filings are tracked so the annual cycle does not depend on someone remembering."),
],
"faqs": [
  ("The recipient says their country has a treaty, so no tax should be deducted.",
   "A treaty rate is available only where the recipient furnishes a tax residency certificate and Form 10F, and where the payment falls within the article relied on. Without those documents the domestic rate applies, and the liability for short deduction sits with the payer in India."),
  ("Is Form 15CA needed for every foreign payment?",
   "No. Certain payments are specified as not requiring it, and for some categories only part of the form is required. Which applies depends on the nature and amount of the remittance, which is exactly what we determine first."),
  ("We are a small company with one foreign related party. Does transfer pricing apply?",
   "If the transaction is with an associated enterprise, the requirement applies regardless of company size, and the accountant's report in Form 3CEB is due on its own timeline. The volume of documentation varies with the value of the transactions."),
  ("A foreign company wants to set up in India. Where do we start?",
   "With the structure — subsidiary, branch, liaison office or project office each carry different tax and FEMA consequences. That choice is easier to make at the start than to reverse afterwards."),
],
"related": ["foreign-income", "pvt-ltd-registration", "tds-returns", "roc-annual-compliance"],
"cta": ("Send the agreement, not just the invoice",
        "Most cross-border questions are answered by the contract. Send it and we will set out the withholding and reporting position in writing."),
},
# ---------------------------------------------------------------- ECOM
{
"slug": "ecommerce-sellers",
"nav": "specialist",
"name": "E-commerce seller compliance",
"short": "E-commerce sellers",
"authority": "CBIC · CBDT",
"title": "E-commerce Seller Compliance — Marketplace Reconciliation, TCS Credit, Multi-state GST",
"meta": "GST and income tax compliance for marketplace sellers: settlement report reconciliation, TCS credit under section 52, multi-state registration for warehouse stock, and return filing.",
"reg": "Marketplace reconciliation, TCS credit and multi-state registration.",
"lead": "Marketplace settlement reports rarely agree with your books on the first pass. Reconciling them before filing is what keeps the notices away.",
"intro": [
  "Selling on a marketplace produces three parallel records: your invoices, the platform's settlement report, and the TCS collected and reported by the operator under section 52. The GST return has to agree with all three, and returns, commission, shipping deductions and cancelled orders are where they diverge.",
  "The second problem is geography. Stock held at a marketplace fulfilment centre in another state usually means a place of business in that state — and therefore a registration, and a return cycle, in each one.",
],
"handle": [
  "Reconciliation of marketplace settlement reports with your sales register and books",
  "TCS credit under section 52 claimed and matched on the portal",
  "Multi-state GST registration where stock is held at fulfilment centres",
  "Treatment of returns, cancellations, commission, shipping and platform fees",
  "GSTR-1 and GSTR-3B filing for each registration on the monthly cycle",
  "Input credit on commission and logistics invoices raised by the platform",
  "Place of supply determination for inter-state orders",
  "Income tax return and books for the selling entity, including presumptive options where eligible",
  "TDS credit under section 194-O reconciled against 26AS",
  "Notices arising from a difference between reported turnover and marketplace data",
],
"supply": [
  "Settlement or payment reports from each marketplace for the period",
  "Order and returns reports, in the platform's export format",
  "Commission and fee invoices raised by the platform",
  "Bank statements showing settlements received",
  "List of fulfilment centres where your stock is held",
  "Existing GST registrations across states",
],
"supply_note": "Export the reports rather than screenshotting the dashboard. Reconciliation depends on order-level data that the summary view does not carry.",
"callout": ("Frequently missed", "Stock in another state's warehouse",
  "A seller who has never left their home state can still have a place of business in four others, because their inventory sits there. This is one of the most common causes of a registration notice for online sellers."),
"steps": [
  ("Platforms and states listed", "We map every marketplace you sell on and every location holding your stock."),
  ("Reports reconciled", "Settlement data is matched to your invoices, with returns and fees separated out."),
  ("Returns filed per state", "Each registration is filed on its own cycle, with TCS credit claimed and matched."),
  ("Annual position closed", "Turnover is reconciled across platforms for the income tax return and the annual GST filing."),
],
"faqs": [
  ("I only sell online and my turnover is small. Do I still need GST registration?",
   "Supply through an e-commerce operator generally requires registration regardless of turnover, with narrow exceptions. Most marketplaces will not let you list without a GSTIN in any case."),
  ("The marketplace already collects TCS. Do I still file returns?",
   "Yes. TCS collected by the operator is a credit in your electronic cash ledger, not a substitute for your own return. It has to be claimed and matched on the portal."),
  ("Why does my reported turnover not match the platform's figure?",
   "Usually returns, cancellations and the treatment of commission and shipping. The platform reports gross order value while your books carry net sales. The difference has to be explainable, which is what the reconciliation produces."),
  ("I sell on three platforms. Is that three sets of everything?",
   "Three sets of reconciliation, but one set of returns per GST registration. We consolidate across platforms before filing so nothing is reported twice."),
],
"related": ["gst-return-filing", "gst-registration", "itr-filing", "trademark-registration"],
"cta": ("Send one month of settlement reports",
        "One month is usually enough to show whether your returns and your marketplace data agree — and where they do not."),
},
# ---------------------------------------------------------------- PVT LTD
{
"slug": "pvt-ltd-registration",
"nav": "start",
"name": "Private limited company registration",
"short": "Company registration",
"authority": "MCA · SPICe+",
"title": "Private Limited Company Registration — SPICe+, DIN, PAN, TAN",
"meta": "Private limited company incorporation through SPICe+ — name approval, DSC and DIN, MOA and AOA, PAN, TAN, EPFO, ESIC and bank-ready documents.",
"reg": "Name approval, DSC, DIN, incorporation, PAN, TAN and bank-ready documents.",
"lead": "Incorporation is a single integrated form now. Getting it right the first time matters, because correcting a wrong structure later costs more than setting it up properly did.",
"intro": [
  "The structure comes before the paperwork. A private limited company suits a business that will raise funds, add shareholders or hold a licence; an LLP suits a professional or family venture that wants limited liability without a board; a proprietorship suits a business that is genuinely one person. We say which one fits before quoting for any of them.",
  "Name approval is the most common stopping point. Names are refused for resembling an existing company, conflicting with a registered trademark, or using a word that requires approval. Checking the trademark register alongside the company register at the start saves a rejected application.",
],
"handle": [
  "Structure advice — private limited, LLP, OPC, partnership or proprietorship",
  "Name search against the company register and the trademark register, and reservation",
  "Digital signature certificates and director identification numbers",
  "MOA and AOA drafted for your actual business objects, not a generic template",
  "Incorporation through SPICe+ with AGILE-PRO, including PAN, TAN, EPFO and ESIC",
  "Registered office documentation, including the owner's NOC and utility proof",
  "Bank account opening documents and the board resolution the bank will ask for",
  "Commencement of business filing in Form INC-20A after capital is brought in",
  "Shareholders' agreement and founder arrangements, drafted on the legal side of the firm",
  "Post-incorporation register maintenance, first board meeting and statutory records",
],
"supply": [
  "PAN and Aadhaar of every proposed director and subscriber",
  "Passport-size photograph and email and mobile of each director",
  "Address proof of each director — bank statement or utility bill, recent",
  "Passport for any foreign national or non-resident director",
  "Registered office proof — utility bill, and rent agreement or ownership document",
  "No objection certificate from the owner of the registered office premises",
  "Two or three proposed names, in order of preference",
],
"supply_note": "Name preferences are worth thinking about before you send them. If the business will eventually need a trademark, choosing a name that can actually be registered saves a rebrand later.",
"callout": ("Read this before filing", "The registered office is not a formality",
  "Every notice from the department, the registry and the tax authority goes to the registered office address. If it is a relative's premises or a temporary space, decide now how post will reach you — a missed notice at that address is treated as a delivered one."),
"steps": [
  ("Structure and name", "We confirm the right entity type and clear your name against both registers before applying."),
  ("Signatures and documents", "DSCs are issued, and identity and premises documents are verified against each other."),
  ("SPICe+ filed", "Incorporation is filed with MOA and AOA drafted for your objects, along with PAN, TAN and registrations."),
  ("Certificate and start-up pack", "You receive the certificate of incorporation, PAN, TAN, and the documents your bank will ask for."),
],
"faqs": [
  ("How many people do I need to start a private limited company?",
   "Two shareholders and two directors, and one of the directors must be resident in India. A one person company is available where there is only one promoter, with its own restrictions."),
  ("How long does incorporation take?",
   "Once name approval is in hand and all documents are signed, it is usually a matter of days rather than weeks. Document readiness — particularly the registered office NOC and address proofs — is the real variable."),
  ("What does it cost?",
   "Two components: our professional fee, and the government fee, which varies with the state of registration, the authorised capital and stamp duty. We quote both separately in writing before starting. Anyone giving a single all-India number without asking about your state is guessing."),
  ("What compliance follows after incorporation?",
   "Commencement of business within the prescribed period, an auditor appointed, annual financial statements and annual return with the registry, director KYC each year, and income tax returns — whether or not the company has traded. We set out the calendar at the time of incorporation."),
],
"related": ["roc-annual-compliance", "gst-registration", "trademark-registration", "international-tax"],
"cta": ("Tell us what the business will actually do",
        "The activity, the number of founders and whether outside funding is likely will settle the structure in one conversation."),
},
# ---------------------------------------------------------------- ROC
{
"slug": "roc-annual-compliance",
"nav": "start",
"name": "ROC annual compliance",
"short": "ROC annual compliance",
"authority": "MCA · Registrar of Companies",
"title": "ROC Annual Compliance — AOC-4, MGT-7, DIR-3 KYC and Statutory Records",
"meta": "Annual filings for companies and LLPs — financial statements in AOC-4, annual return in MGT-7, director KYC, board and general meeting records, and event-based forms.",
"reg": "Financials, board minutes, annual return and director KYC in one package.",
"lead": "Annual filings carry a daily additional fee once the date passes, and it does not stop accruing. This is the one compliance head where delay has a running price tag.",
"intro": [
  "Registry compliance is unforgiving in a specific way: the additional fee for late filing runs per day, without a ceiling in most cases, and directors of a company that fails to file for a continued period face disqualification. A dormant company that never traded is not exempt from any of this.",
  "The work is also more than two forms. Board meetings have to be held and minuted, an auditor appointed and any casual vacancy filled, registers maintained, and event-based forms filed when a director changes, capital is allotted or a charge is created.",
],
"handle": [
  "Financial statements filed in Form AOC-4, with XBRL where applicable",
  "Annual return in Form MGT-7 or MGT-7A for small companies and OPCs",
  "LLP annual filings — Form 8 statement of account and Form 11 annual return",
  "Director KYC each year in DIR-3 KYC or the web-based confirmation",
  "Board meeting and annual general meeting notices, minutes and resolutions",
  "Auditor appointment in Form ADT-1, and filling of a casual vacancy",
  "Statutory registers — members, directors, charges and share transfers",
  "Event-based filings — director change, registered office shift, share allotment and transfer",
  "Charge creation, modification and satisfaction with the registry",
  "Condonation and compounding where filings were missed in earlier years",
],
"supply": [
  "Trial balance and final accounts for the year",
  "Audit report and the auditor's signed financial statements",
  "Board and general meeting details for the year, with attendance",
  "Details of any director change, allotment or charge during the year",
  "Previous year's filed forms and their challans",
  "Digital signatures of the director signing, and of the professional certifying",
],
"supply_note": "If earlier years are also pending, send those details at the same time. The forms are sequential and the cost of clearing a backlog is easier to quote once, not year by year.",
"callout": ("Costs run daily", "Missed last year's filing?",
  "The additional fee accrues per day of delay, so the answer to \u201cshall we do it next month\u201d is always that next month is more expensive. Where the delay is long, condonation or compounding may be the cleaner route, and we will say which applies."),
"steps": [
  ("Position reviewed", "We check what has been filed, what is pending and what the accumulated exposure is."),
  ("Records prepared", "Minutes, resolutions and registers are brought up to date alongside the financials."),
  ("Forms certified and filed", "AOC-4, MGT-7 and the supporting forms are filed with the required certification."),
  ("Calendar issued", "You receive next year's dates, so the cycle runs without a reminder from the registry."),
],
"faqs": [
  ("My company has no business activity. Do I still need to file?",
   "Yes. Annual filings, director KYC and income tax returns apply to a dormant company as much as to a trading one. If the company is genuinely not going to trade, striking it off or obtaining dormant status is a decision worth taking rather than leaving it to accumulate fees."),
  ("What happens if filings are missed for years?",
   "Additional fees accumulate, the company can be struck off by the registry, and directors can be disqualified for a period, which affects their directorships in other companies as well. The position is recoverable, but the route depends on how long it has run."),
  ("Is an LLP treated the same way?",
   "The forms differ — Form 8 and Form 11 rather than AOC-4 and MGT-7 — and the due dates are different, but the daily additional fee for delay applies equally. LLPs are not the lighter option that they are often assumed to be on this point."),
  ("Can you take over from our existing consultant mid-year?",
   "Yes, and it is common. We start by reconciling what is on the registry record against what we are told has been filed — those two do not always agree."),
],
"related": ["pvt-ltd-registration", "itr-filing", "tds-returns", "international-tax"],
"cta": ("Send your company name or CIN",
        "We will pull the filing history from the public record and tell you exactly what is pending before quoting."),
},
# ---------------------------------------------------------------- TRADEMARK
{
"slug": "trademark-registration",
"nav": "ip",
"name": "Trademark registration",
"short": "Trademark registration",
"authority": "CGPDTM · Trade Marks Registry",
"title": "Trademark Registration — Search, Filing, Objection Reply and Opposition",
"meta": "Trademark search, class selection and filing in Form TM-A, examination report replies, opposition and hearings, plus copyright, design and Madrid protocol filings.",
"reg": "Class advice, public-register search, filing and objection reply if it comes.",
"lead": "The search matters more than the filing. Most refusals are visible on the public register before an application is ever made.",
"intro": [
  "A mark is registered class by class, for the goods or services actually covered. Filing in the wrong class leaves the business you actually run unprotected, and filing in every class costs money for protection you cannot defend.",
  "An examination report is not a rejection. It is a stage most applications pass through, and it carries a reply window. Replied to properly, with evidence of use where the objection is about distinctiveness, a large share of these applications proceed.",
],
"handle": [
  "Search of the public register, and advice on whether the mark is worth filing as proposed",
  "Class selection under the Nice classification for your actual goods and services",
  "Application in Form TM-A, for a word mark, device mark or both",
  "Reply to the examination report, with evidence of use where distinctiveness is questioned",
  "Show cause hearings before the Registrar",
  "Opposition filed against a conflicting mark, and defence of an opposition against yours",
  "Renewal, assignment, and recording a change of proprietor name or address",
  "Copyright registration for artistic work, literary work and software",
  "Design registration for the shape and appearance of a product",
  "International filing through the Madrid protocol, and national filings abroad",
],
"supply": [
  "The mark — the exact wording, or the logo file in a clear format",
  "A list of the goods or services it is used for, in plain description",
  "Date of first use, and evidence of it if the mark is already in the market",
  "Applicant details — PAN, and constitution document for a company, LLP or firm",
  "Udyam or MSME certificate, where a concessional fee is claimed",
  "Power of attorney in Form TM-48, which we prepare for signature",
],
"supply_note": "If the mark is already in use, evidence of use from the earliest date is worth collecting now — invoices, packaging, advertisements. It is the single most useful thing to have if an objection comes.",
"callout": ("Order of operations", "Naming a new company?",
  "Check the trademark register before you reserve the company name, not after. A name approved by the company registry can still infringe a registered mark, and the rebrand is far more expensive than the search was."),
"steps": [
  ("Search and advice", "We search the register and tell you plainly whether the mark is filable as it stands, or needs changing."),
  ("Class and filing", "Classes are selected against your real goods and services, and the application is filed with the TM number issued immediately."),
  ("Examination reply", "If an examination report comes, the reply is drafted and filed within the window, with evidence where needed."),
  ("Publication and registration", "The mark is advertised in the journal, and if no opposition follows, the registration certificate is issued."),
],
"faqs": [
  ("Can I use the ™ symbol before registration?",
   "The ™ symbol can be used once an application is filed. The ® symbol may be used only after the mark is registered, and using it earlier is itself an offence."),
  ("How long does registration take?",
   "The application number is issued immediately, and protection is claimed from the date of filing. Registration itself depends on whether an examination report or an opposition arises, and can run from several months to considerably longer."),
  ("Someone is already using my name. Is there anything to do?",
   "It depends on who used it first, whether either party has registration, and in which class and territory. Prior use carries weight in Indian law even without registration, so the facts and the dates decide this rather than the register alone."),
  ("Do I need to register in every class?",
   "No. Register where you trade and where you realistically will. Over-filing is expensive to maintain and vulnerable to removal for non-use."),
],
"related": ["pvt-ltd-registration", "ecommerce-sellers", "fssai-licence", "gst-registration"],
"cta": ("Send the mark and what it sells",
        "A search takes a short time and settles the most important question before any fee is spent."),
},
# ---------------------------------------------------------------- FSSAI
{
"slug": "fssai-licence",
"nav": "licence",
"name": "FSSAI licence and registration",
"short": "FSSAI licence",
"authority": "FSSAI · Food Safety and Standards Authority",
"title": "FSSAI Licence &amp; Registration — Basic, State and Central",
"meta": "FSSAI basic registration, state licence and central licence — tier assessment, application, renewal, modification and annual return filing for food businesses.",
"reg": "Basic, state or central — we confirm the right tier before applying.",
"lead": "Three tiers, and applying under the wrong one is the most common reason a food business ends up re-applying.",
"intro": [
  "Which licence you need is decided by turnover, the nature of the operation, and whether you operate in more than one state. A manufacturer, an importer and a home kitchen sit at different tiers, and an operation that crosses a threshold mid-year has to upgrade rather than wait for renewal.",
  "Food businesses also carry obligations after the licence is granted — display of the licence number, annual return for certain categories, and a hygiene standard that is inspected rather than declared. We set those out at the start instead of leaving them to the first inspection.",
],
"handle": [
  "Tier assessment — basic registration, state licence or central licence",
  "Application with product category selection matched to what you actually make or sell",
  "Licences for manufacturers, restaurants, cloud kitchens, traders, transporters and storage",
  "Importer licence, which is central regardless of turnover",
  "E-commerce food seller registration for marketplace listings",
  "Renewal before expiry, and modification for added products or premises",
  "Annual return filing where the category requires it",
  "Layout and equipment documentation for manufacturing licences",
  "Reply to improvement notices and inspection observations",
  "Label review against packaging and display requirements",
],
"supply": [
  "Identity and address proof of the proprietor, partners or directors",
  "Premises proof — rent agreement or ownership document, with a utility bill",
  "List of food products or categories handled",
  "Layout plan of the premises, for a manufacturing licence",
  "List of equipment and machinery, with capacity, for manufacturers",
  "Water test report from a recognised laboratory, where required",
  "Form IX nomination, and the food safety management plan",
],
"supply_note": "Turnover and capacity decide the tier, so send realistic figures rather than conservative ones. Applying at a lower tier and crossing the threshold later means applying again.",
"callout": ("Applies to more businesses than expected", "Selling food online or from home?",
  "Cloud kitchens, home bakers and marketplace food sellers are food businesses under the Act. Most marketplaces will not accept a listing without the number, and the basic registration tier exists precisely for operations of this size."),
"steps": [
  ("Tier confirmed", "Turnover, activity and states of operation are checked, and the correct licence tier is fixed."),
  ("Documents prepared", "Premises, product and equipment documentation is assembled to match the tier applied for."),
  ("Application filed", "The application goes in and any query raised by the authority is answered within the window."),
  ("Licence and calendar", "The licence is issued, and you receive the renewal date and any annual return obligation in writing."),
],
"faqs": [
  ("I run a small tea stall. Do I need this?",
   "A food business at the smallest scale generally needs basic registration rather than a licence. It is inexpensive and it is the tier designed for exactly that operation."),
  ("How long is a licence valid?",
   "It can be taken for a period of one to five years, and renewal has to be applied for before expiry. Allowing it to lapse means applying afresh, with the business unlicensed in the meantime."),
  ("We are adding a new product line. Does the existing licence cover it?",
   "Only if the category was declared. Adding products outside the declared categories requires a modification of the licence, which is a simpler process than a fresh application but is not optional."),
  ("Do I need a separate licence for each outlet?",
   "Generally each premises needs its own registration or licence, and operations across states can push you to the central tier. The count of outlets and their locations settles this."),
],
"related": ["gst-registration", "trademark-registration", "pvt-ltd-registration", "itr-filing"],
"cta": ("Tell us what you make or sell, and where",
        "Product, turnover and number of states — three facts that settle the tier before any application is made."),
},
]

SERVICE_BY_SLUG = {s["slug"]: s for s in SERVICES}

# ----------------------------------------------------------------------
# The full service register (services.html) — every practice area.
# (label, page-slug or None)
# ----------------------------------------------------------------------

REGISTER = [
    {
        "id": "start",
        "authority": "MCA · Registrar of Companies",
        "title": "Start a business",
        "intro": "Choosing the structure, then getting it on the register — and the filings that follow in the first year.",
        "items": [
            ("Private limited company registration", "Name approval, DSC and DIN, SPICe+ incorporation, PAN and TAN.", "pvt-ltd-registration"),
            ("LLP registration", "Incorporation, LLP agreement drafting and filing with the registry.", None),
            ("One person company", "Incorporation for a single promoter, with the nominee and the restrictions explained.", None),
            ("Partnership firm and proprietorship", "Deed drafting, registration where required, PAN and the registrations that follow.", None),
            ("Section 8 company, trust and society", "Formation for charitable objects, with the governing document drafted for the activity.", None),
            ("ROC annual compliance", "AOC-4, MGT-7, director KYC, minutes and statutory registers.", "roc-annual-compliance"),
            ("Event-based ROC filings", "Director change, share allotment and transfer, registered office shift, charge creation.", None),
            ("Udyam and MSME registration", "Registration and certificate, plus what it actually unlocks for you.", None),
            ("Importer exporter code", "IEC application, modification and linking with GST and customs records.", None),
            ("EPF and ESI registration", "Employer registration, and the monthly return cycle that follows it.", None),
            ("Strike off and winding up", "Closing a company or LLP cleanly rather than letting fees accumulate.", None),
            ("Overseas incorporation", "Entity set-up abroad, coordinated with Indian reporting under FEMA.", None),
        ],
    },
    {
        "id": "tax",
        "authority": "CBDT · CBIC",
        "title": "Tax and recurring compliance",
        "intro": "The work that quietly decides whether you receive a notice — filed on a fixed cycle rather than at the deadline.",
        "items": [
            ("Income tax return filing", "Individuals, firms and companies, reconciled against 26AS and the AIS.", "itr-filing"),
            ("TDS computation and returns", "Section-wise computation, challan mapping, 24Q/26Q/27Q and Form 16.", "tds-returns"),
            ("GST registration", "Application, clarification replies and GSTIN, including e-commerce sellers.", "gst-registration"),
            ("GST return filing", "GSTR-1 and 3B with 2B reconciliation and input credit review.", "gst-return-filing"),
            ("GST annual return and audit", "GSTR-9 and 9C, with the year reconciled before it is certified.", None),
            ("GST refunds", "Export without payment of tax, inverted duty structure and excess cash balance.", None),
            ("Tax audit and statutory audit", "Audit under the Income-tax Act and the Companies Act, with the report and annexures.", None),
            ("Accounting and bookkeeping", "Monthly books, reconciliations and management reporting on a fixed calendar.", None),
            ("Payroll processing", "Salary computation, TDS on salary, PF and ESI returns and Form 16.", None),
            ("CMA data and project reports", "Estimated and provisional statements prepared for bank credit proposals.", None),
            ("Notices, scrutiny and appeals", "GST and income tax notices, assessment representation and appeals.", None),
            ("Crypto and VDA taxation", "Section 115BBH computation, 194S credit and Schedule VDA.", "crypto-tax"),
        ],
    },
    {
        "id": "ip",
        "authority": "CGPDTM",
        "title": "Trademark and intellectual property",
        "intro": "Securing the name, the mark and the design before somebody else does — and defending it when they try.",
        "items": [
            ("Trademark search and registration", "Class advice, public-register search, filing and objection reply if it comes.", "trademark-registration"),
            ("Examination report reply", "Reply to the objection with evidence of use, and hearings before the Registrar.", "trademark-registration"),
            ("Opposition and rectification", "Opposing a conflicting mark, defending yours, and removal for non-use.", None),
            ("Trademark renewal and assignment", "Renewal before expiry, assignment, and recording a change of proprietor.", None),
            ("Copyright registration", "Artistic, literary, musical and software works.", None),
            ("Design registration", "Protection for the shape, configuration and appearance of a product.", None),
            ("Patent filing", "Provisional and complete specification, drafted with a technical expert.", None),
            ("International trademark filing", "Madrid protocol applications and national filings abroad.", None),
        ],
    },
    {
        "id": "licence",
        "authority": "FSSAI · BIS · RBI · SEBI",
        "title": "Licences and regulatory approvals",
        "intro": "Sector approvals, where the paperwork is effectively part of the business model.",
        "items": [
            ("FSSAI licence and registration", "Basic, state or central — we confirm the right tier before applying.", "fssai-licence"),
            ("ISO certification", "9001, 14001, 22000 and others, through accredited certification bodies.", None),
            ("BIS certification and hallmarking", "Product certification, and registration under the compulsory schemes.", None),
            ("Drug licence and AYUSH licence", "Retail, wholesale and manufacturing licences for pharmaceutical and AYUSH products.", None),
            ("PSARA licence", "Private security agency licensing, including training tie-up requirements.", None),
            ("Legal metrology registration", "Packaged commodity registration and declaration requirements.", None),
            ("NBFC registration", "Application to the Reserve Bank, with the capital and fit-and-proper requirements.", None),
            ("FFMC and payment aggregator approvals", "Applications for money changing and payment service authorisations.", None),
            ("FEMA, FDI and ODI reporting", "FC-GPR, FC-TRS, the annual performance return and FLA filings.", "international-tax"),
            ("Shop and establishment registration", "State-level registration, and the labour records that follow.", None),
            ("Trade licence and municipal approvals", "Local body licensing for premises and activity.", None),
            ("Labour law compliance", "Registers, returns and statutory displays under the labour codes.", None),
        ],
    },
    {
        "id": "env",
        "authority": "CPCB · State pollution control boards",
        "title": "Environment and EPR",
        "intro": "Consents and extended producer responsibility duties for anyone who manufactures, imports or brands a product.",
        "items": [
            ("Consent to establish and operate", "State pollution control board consents, with category assessment first.", None),
            ("EPR registration — plastic packaging", "Producer, importer and brand owner registration, with annual target filing.", None),
            ("EPR — e-waste, battery and tyre", "Registration and annual returns under the respective waste management rules.", None),
            ("Hazardous waste authorisation", "Authorisation, manifest records and annual returns.", None),
            ("Environmental clearance and EIA", "Clearance applications and coordination of the impact assessment.", None),
            ("Environmental audit and ESG reporting", "Compliance audit, and sustainability reporting for larger entities.", None),
        ],
    },
    {
        "id": "legal",
        "authority": "Advocate-led",
        "title": "Legal drafting and representation",
        "intro": "The side of the practice that begins where a filing ends — a reply, a notice, or somebody appearing for you.",
        "items": [
            ("Notices and replies", "Legal notices issued and replied to, including cheque dishonour matters.", None),
            ("Agreements and deeds", "Commercial contracts, partnership and LLP agreements, sale and lease deeds.", None),
            ("Shareholders and founders agreements", "Terms drafted for what actually happens when founders disagree.", None),
            ("Recovery and cheque bounce", "Proceedings under section 138 and civil recovery suits.", None),
            ("Consumer and commercial disputes", "Complaints, replies and representation before the appropriate forum.", None),
            ("Tax and GST litigation", "Appeals, representation before appellate authorities and writ matters.", None),
            ("POSH compliance", "Policy, committee constitution, training and the annual report.", None),
            ("Due diligence and legal opinion", "Written opinion on a transaction, title or compliance position.", None),
        ],
    },
]

# ----------------------------------------------------------------------
# Homepage — frequently requested tiles
# ----------------------------------------------------------------------

TILES = [
    ("MCA / SPICe+", "Private limited company", "Name approval, DSC, DIN, incorporation, PAN, TAN and bank-ready documents.", "pvt-ltd-registration"),
    ("GST / REG-01", "GST registration", "Application, clarification replies and GSTIN, including for e-commerce sellers.", "gst-registration"),
    ("GSTR-1 / 3B", "Monthly GST returns", "Reconciliation with 2B, input credit review and filing on a fixed monthly cycle.", "gst-return-filing"),
    ("24Q / 26Q", "TDS returns", "Section-wise computation, challan mapping, quarterly returns and Form 16 or 16A.", "tds-returns"),
    ("ITR", "Income tax return", "Individuals, firms and companies — with a computation you can actually read.", "itr-filing"),
    ("TM-A", "Trademark registration", "Class advice, public-register search, filing and objection reply if it comes.", "trademark-registration"),
    ("AOC-4 / MGT-7", "ROC annual compliance", "Financials, board minutes, annual return and director KYC in one package.", "roc-annual-compliance"),
    ("FSSAI", "FSSAI licence", "Basic, state or central — we confirm the right tier before applying.", "fssai-licence"),
    ("115BBH", "Crypto and VDA tax", "Trade-wise computation, 194S credit and Schedule VDA that reconciles.", "crypto-tax"),
    ("15CA / 15CB", "Foreign remittance", "Withholding under section 195, treaty rate and certification before the transfer.", "international-tax"),
    ("Marketplace", "E-commerce sellers", "Settlement reconciliation, TCS credit and registration in every stocking state.", "ecommerce-sellers"),
    ("NRI", "Foreign income and NRI", "Residential status, Schedule FA, treaty relief and repatriation.", "foreign-income"),
]

PRACTICES = [
    ("MCA · ROC", "Start a business", "Choosing the structure, then getting it on the register.",
     ["Pvt Ltd, LLP, OPC, partnership", "Section 8, trust, society", "MSME, IEC, EPF, ESI", "Overseas incorporation"],
     "services.html#start", "Start a registration"),
    ("CBIC · CBDT", "Tax and compliance", "The recurring work that quietly decides whether you get a notice.",
     ["GST registration and returns", "TDS computation and returns", "Income tax filing and audit", "ROC annual compliance"],
     "services.html#tax", "See what recurs monthly"),
    ("CGPDTM", "Trademark and IP", "Securing the name, mark and invention before someone else does.",
     ["Search, filing, objection reply", "Opposition and hearings", "Copyright, design, patent", "Madrid and foreign filing"],
     "trademark-registration.html", "Check your mark"),
    ("RBI · SEBI · BIS", "Licences and regulatory", "Sector approvals, where the paperwork is the business model.",
     ["FSSAI, drug, AYUSH, PSARA", "ISO, BIS, CE, hallmark", "NBFC, FFMC, payment licences", "FEMA and FDI reporting"],
     "services.html#licence", "Check what applies"),
    ("CPCB · SPCB", "Environment", "Consents and EPR duties for anyone who manufactures, imports or brands.",
     ["Consent to establish and operate", "EPR — plastic, e-waste, battery", "Hazardous waste authorisation", "EIA, audits, ESG reporting"],
     "services.html#env", "Assess your obligation"),
    ("Advocate-led", "Legal and representation", "Where a filing ends and somebody has to reply, draft or appear.",
     ["Notices, replies, agreements", "Cheque bounce and recovery", "Tax and GST litigation", "POSH and due diligence"],
     "services.html#legal", "Describe the dispute"),
]

HOME_FAQS = [
    ("How quickly can a company be registered?",
     "Once name approval and signed documents are in hand, incorporation is usually a matter of days rather than weeks. The variable is document readiness — identity proofs, address proof for the registered office and the no objection certificate from the property owner. We give you a realistic date at the scope stage, not an optimistic one."),
    ("What will it cost?",
     "Two components: our professional fee, and the statutory or government fee, which is fixed by the authority and varies with state, authorised capital, turnover or category. We quote both separately in writing before starting. Anyone quoting a single all-India number without asking about your state is guessing."),
    ("Do I need to visit an office?",
     "No. Most matters run entirely online — documents collected digitally, signatures through a digital signature certificate or e-sign. If you would rather sit across a desk, any of our five offices works."),
    ("Can you work with clients based outside India?",
     "Yes. Non-resident founders, NRI taxpayers and foreign parent companies are a regular part of the practice. Everything is delivered from India, and we handle apostille and notarisation requirements where the authority asks for them."),
    ("I already have an accountant. Can you handle only part of the work?",
     "Yes. Many clients keep their existing bookkeeping and bring us in for licensing, trademark, ROC or a specific notice. We will not push a bundle you do not need."),
    ("I received a notice. What now?",
     "Send it across before the reply window closes — GST, income tax, ROC and pollution board notices all carry deadlines, and an extension is easier to obtain before the date than after. We read it, tell you how serious it is, and quote for the reply."),
]

CALENDAR = [
    ("07", "TDS and TCS deposit", "Tax deducted during the previous month"),
    ("11", "GSTR-1", "Outward supplies, for monthly filers"),
    ("15", "PF and ESI", "Employer and employee share"),
    ("20", "GSTR-3B", "Summary return and payment of tax"),
]
